language: csharp
solution: "./CloudIpspSDK.sln"
install:
    - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./CloudIpspSDK.sln
script:
    - xbuild ./CloudIpspSDK.sln
    - dotnet vstest CloudIpspSdkTest/bin/Debug/CloudIpspSdkTest.dll